files_in = "{filein}"
file_out = "{fileout}"

# compression library
compression = 'ZLIB4'

# run number
run_number = 0
detector_db = "next100"

# How frequently to print events
print_mod = 1

pmt_wfs_rebin = 1
pmt_pe_rms = 0.346
sipm_noise_cut = 0.0 * pes
filter_padding = 50

# max number of events to run
event_range = all

# Set thresholds for calibrated sum
thr_csum_s1 = 0.1 * pes
thr_csum_s2 = 0.1 * pes

# Set parameters to search for S1
# Notice that in MC file S1 is in t=100 mus
s1_tmin       =   9 * mus # position of S1 in MC files at 100 mus
s1_tmax       =  11 * mus # change tmin and tmax if S1 not at 100 mus
s1_stride     =   4       # minimum number of 25 ns bins in S1 searches
s1_lmin       =   4       # 8 x 25 = 200 ns
s1_lmax       =  40       # 20 x 25 = 500 ns
s1_rebin_stride = 1       # Do not rebin S1 by default

# Set parameters to search for S2
s2_tmin     =     11 * mus # assumes S1 at 100 mus, change if S1 not at 100 mus
s2_tmax     =   1500 * mus # end of the window
s2_stride   =     40       #  40 x 25 = 1   mus
s2_lmin     =     80       #  80 x 25 = 2.0 mus
s2_lmax     = 100000       # maximum value of S2 width
s2_rebin_stride = 40       # Rebin by default, 40 25 ns time bins to make one 1us time bin

pmt_samp_wid  = 25 * ns
sipm_samp_wid =  1 * mus

cutting_function = pyrrha
cutting_params   = dict(selection_method    = median_std_method,
                        selection_kwargs    = {'nsigma': 3},
                        proximity_threshold = 25,
                        padding_radius      = 75,
                        run_number          = run_number,
                        detector_db         = detector_db)