files_in    = "{files_in}"
file_out    = "{files_out}"
compression = "ZLIB4"
run_number  = 0
detector_db = "next100"
print_mod   = 10000
event_range = all

drift_v     = 0.87 * mm / mus

s1_params = dict(
s1_nmin     =    0,
s1_nmax     =    100,
s1_emin     =    5 * pes,
s1_emax     =  1e9 * pes,
s1_wmin     =   75 * ns,
s1_wmax     =    2 * mus,
s1_hmin     =    2 * pes,
s1_hmax     =  1e9 * pes,
s1_ethr     =    0 * pes,
)

s2_params = dict(
s2_nmin     =    1,
s2_nmax     =    1e3,
s2_emin     =  100 * pes,
s2_emax     =  1e9 * pes,
s2_wmin     =  0.5 * mus,
s2_wmax     = 1400 * mus,
s2_hmin     =  100 * pes,
s2_hmax     =  1e9 * pes,
s2_ethr     =    0 * pes,
s2_nsipmmin =    1,
s2_nsipmmax = 9000,
)

rebin = 4
rebin_method = stride

sipm_charge_type = raw

global_reco_algo = barycenter
global_reco_params = dict(Qthr = 1 * pes)

same_peak = True

corrections = dict(
  filename    = "$ICDIR/database/test_data/MC_3Dmap_fullsim_0705.h5",
  apply_temp  = False,
  norm_method = maximum,
  apply_z     = False,
)

clustering_params = dict(
    min_samples  =     5,
    scale_xy     = 15.55,
    scale_z      =   4.0
)

q_thr = 5 * pes
