# nexus.sub

# The job title here.
#jobname=NEXT100_Kr83m
jobname=NEXT100_Kr83m_Full
#jobname=NEXT100_Th228_Port1a
#jobname=NEXT100_Th228_Port1a_DEP
#jobname=NEXT100_Th228_Port1a_FSPECT
#jobname=NEXT100_Th228_Port1a_DEP_Full
#jobname=NEXT100_alpha

OSDF_LOCATION=osdf:///ospool/ap40/data/krishan.mistry
HOME_LOCATION=/home/krishan.mistry/code/NEXT100Production/NEXT100

pressure=4bar

# newjobid = $(Process) + 100
#NewProcess = $INT(newjobid, %d)
NewProcess = $(Process)

executable = $(jobname).sh
#executable = NEXT100_Th228_Port1a.sh

arguments = $(NewProcess) $(jobname) $(pressure)

# Specify the name of the log, standard error, and standard output (or "screen output") files. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
log    = jobs/$(jobname)/$(pressure)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).log
error  = jobs/$(jobname)/$(pressure)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).err
output = jobs/$(jobname)/$(pressure)/jobid$(NewProcess)/$(Cluster)_$(NewProcess).out

# Transfer input files
transfer_input_files = $(HOME_LOCATION)/tar/$(pressure)/files_$(pressure).tar

# Transfer output files
transfer_output_remaps = "$(jobname).tar = $(OSDF_LOCATION)/job/Production/$(jobname)/$(pressure)/$(jobname)_$(Cluster)_$(NewProcess).tar"

# Specify Job duration category as "Medium" (expected runtime <10 hr) or "Long" (expected runtime <20 hr). 
+JobDurationCategory = "Medium"
#+JobDurationCategory = "Long"

# Use a singularity image to submit the file. The image should be stored in the protected area of your workspace
container_image = osdf:///ospool/ap40/data/krishan.mistry/containers/icnexusv17.sif

# Tell HTCondor requirements (e.g., operating system) your job needs, 
# what amount of compute resources each job will need on the computer where it runs.
requirements = (Arch == "X86_64" && TARGET.GLIDEIN_ResourceName =!= "Lehigh - Hawk" && TARGET.GLIDEIN_ResourceName =!= "UA-LR-ITS-EP")
request_cpus = 1
request_memory = 500MB
retry_request_memory = 2GB
request_disk = 5GB

# If submitting more than 10k jobs use this statement
max_idle = 2000

# Tell HTCondor the number of instances to run:
queue 25000